# Generated by Django 4.1.7 on 2023-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RD_auth", "0002_user_biz_name_user_shop_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lat",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="lon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
