# Generated by Django 4.2.2 on 2023-06-10 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("RD_auth", "0003_user_lat_user_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestMec",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("pending", models.BooleanField(default=True)),
                (
                    "driver_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "driver_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mec_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanic",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Request Mechanic",
                "db_table": "Request Mechanic",
            },
        ),
    ]
