# Generated by Django 4.2.2 on 2023-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RD_auth", "0004_requestmec"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requestmec", old_name="driver_location", new_name="lat",
        ),
        migrations.AddField(
            model_name="requestmec",
            name="lon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
