# Generated by Django 4.2.2 on 2023-06-10 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("RD_auth", "0005_rename_driver_location_requestmec_lat_requestmec_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmec",
            name="date_requested",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="date_requested",
            ),
            preserve_default=False,
        ),
    ]
